version: 1.0.{build}
environment:
  matrix:
  - CYG_ROOT: C:\cygwin64
    BASH: C:\cygwin64\bin\bash
    CC: gcc
    CYG_PACKAGES: ruby
    CYG_SETUP: C:\cygwin64\setup-x86_64.exe
  - MSYSTEM: MINGW64
    BASH: C:\msys64\usr\bin\bash
    CC: x86_64-w64-mingw32-gcc
    MSYS_PACKAGES: mingw-w64-x86_64-ruby 
    PATH: c:\msys64\mingw64\usr\bin;c:\msys64\mingw64\bin;%PATH%
install:
- cmd: >-
    if defined CYG_ROOT (%CYG_SETUP% --quiet-mode --no-shortcuts --only-site --root "%CYG_ROOT%" --packages "%CYG_PACKAGES%" --upgrade-also)

    if defined MSYSTEM (%BASH% -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz")
    if defined MSYSTEM (%BASH% -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig")
    if defined MSYSTEM (%BASH% -lc "pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz{.sig,}")
    if defined MSYSTEM (%BASH% -lc "pacman -U msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz")
    if defined MSYSTEM (%BASH% -lc "pacman -Suuy --noconfirm ${MSYS_PACKAGES}")

    if defined MSYSTEM (%BASH% -lc "pacman -Suuy --noconfirm ${MSYS_PACKAGES} && pacman -Sc --noconfirm")
build_script:
- cmd: if defined BASH (%BASH% -lc "cd $(cygpath ${APPVEYOR_BUILD_FOLDER}) && rake")
test_script:
- cmd: if defined BASH (%BASH% -lc "cd $(cygpath ${APPVEYOR_BUILD_FOLDER}) && rake test")
